# Generated by Django 3.1.6 on 2022-07-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='Applying_For',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
